---
title: "Week 07 Data visualization"
subtitle: "Open and reproducible science: general reasons and approaches"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
show_results <- TRUE
hide_results <- function(input, show=TRUE){
  if(show){
    return(input)
  } else{
    return("")
  }
}
```



```{r, include=show_results}
library(tidyverse)
```

# Homework solutions

## Task 1: data exploration


```{r}
climatedf_comp <- read.csv(here::here("html","climate_data.csv"))
```


### 1.1 First look


```{r, include=show_results}
head(climatedf_comp, n=3)
summary(climatedf_comp)
```

### 1.2 Which has been the hottest year?


```{r, include=show_results}
climatedf_comp %>% 
  dplyr::group_by(Year) %>% 
  dplyr::summarise(mean_temp=mean(Annual_temperature)) %>% 
  dplyr::filter(mean_temp==max(mean_temp)) %>% 
  dplyr::pull(Year)
```


### 1.3 Which has been the coldest year?


```{r, include=show_results}
climatedf_comp %>% 
  dplyr::group_by(Year) %>% 
  dplyr::summarise(mean_temp=mean(Annual_temperature)) %>% 
  dplyr::filter(mean_temp==min(mean_temp)) %>% 
  dplyr::pull(Year)
```


## Task 2: visualization


### 2.1 Association of `Annual_temperature` and `Year`



```{r, include=show_results}
climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>%
  ggplot() +
  geom_line(aes(Year, Annual_temperature, color=Location)) +
  labs(y="Annual temperature")
```


### 2.2 Add information on the altitude



```{r, include=show_results}
climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>%
  ggplot() +
  geom_line(aes(Year, Annual_temperature, color=Altitude,group=Location)) +
  geom_label(aes(Year,Annual_temperature,label=Location),data = climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% 
    dplyr::filter(Year==min(Year)+5),nudge_y = 1) +
  labs(y="Annual temperature")
```


### 2.3 Normalization



```{r, include=show_results}
climatedf_comp_translated <- climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% 
  dplyr::group_by(Location) %>% 
  dplyr::mutate(mean_temperature = mean(Annual_temperature[Year<1951]),
                Annual_temperature = Annual_temperature-mean_temperature)

ggplot(climatedf_comp_translated) +
  geom_line(aes(Year, Annual_temperature, color=Altitude,group=Location)) +
  labs(y="Annual temperature deviation from average up to 1951")
```


### 2.4 Associations between `Annual_Precipitation`, and `Sunshine_duration`



```{r, include=show_results}
climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>%
  ggplot() +
  geom_point(aes(Annual_Precipitation, Sunshine_duration, color=Location))
```



```{r, include=show_results}
climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti"))%>% 
  ggplot() +
  geom_violin(aes(Location,Annual_Precipitation, color= Sunshine_duration)) +
  ggforce::geom_sina(aes(Location,Annual_Precipitation, color= Sunshine_duration))
```
```{r, include=show_results}
climatedf_comp %>% 
  dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti"))%>% 
  ggplot() +
  geom_boxplot(aes(Location,Sunshine_duration , color= Annual_Precipitation)) +
  geom_jitter(aes(Location,Sunshine_duration, color= Annual_Precipitation))
```





<!-- ## Task 3: aggregated data -->

<!-- In this task we will look at a situation where we only have aggregated data: The mean and standard deviation of `Annual_summer_days` for the years 1931-1960, 1961-1990 and 1991-2020. The following code creates this aggregated data that we will use: -->

<!-- ```{r, include=show_results} -->
<!-- library(magrittr) # for the pip `%>%`  -->
<!-- cutv <- c(1930,1960,1990,2020) -->
<!-- climatedf_comp_aggr <- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   dplyr::mutate(Year = cut(Year, cutv, right = TRUE), -->
<!--                 Year = factor(Year, labels = c("1931-1960","1961-1990","1991-2020"))) %>%  -->
<!--   dplyr::group_by(Year, Location) %>%  -->
<!--   dplyr::summarise("mean_Annual_summer_days" = mean(na.omit(Annual_summer_days)), -->
<!--                    "sd_Annual_summer_days" = sd(na.omit(Annual_summer_days)))  -->
<!-- ``` -->


<!-- ### 3.1  -->
<!-- Find a good representation of showing the association between `Year` and `mean_Annual_summer_days` and create a plot. -->


<!-- ```{r} -->
<!-- climatedf_comp_aggr %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year, mean_Annual_summer_days, fill=Location), position = "dodge") + -->
<!--   theme(axis.text.x = element_text(angle=45,hjust=1)) + -->
<!--   labs(x="", y="Mean number of annual summer days") -->
<!-- ``` -->


<!-- ### 3.2 -->
<!-- Adapt your previous plot by incorporating the given uncertainty (`sd_Annual_summer_days`). -->


<!-- ```{r} -->
<!-- climatedf_comp_aggr %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year, mean_Annual_summer_days, fill=Location), position = "dodge") + -->
<!--   geom_errorbar(aes(x=Year, -->
<!--                   y=mean_Annual_summer_days, -->
<!--                   ymin=mean_Annual_summer_days-2*sd_Annual_summer_days,  -->
<!--                   ymax=mean_Annual_summer_days+2*sd_Annual_summer_days, group=Location), position = "dodge") + -->
<!--   theme(axis.text.x = element_text(angle=45,hjust=1)) + -->
<!--   labs(x="", y="Mean number of annual summer days") -->
<!-- ``` -->










<!-- # 2 -->

<!-- ```{r, include=show_results} -->
<!-- plotvars <- colnames(climatedf_comp)[c(-1,-2,-4)] -->
<!-- plotvar <- plotvars[3] -->
<!-- colorvar <- plotvars[1] -->
<!-- ``` -->

<!-- In this exercise we will build a visualization step by step starting from the following plot: -->

<!-- ```{r, include=show_results} -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year, Annual_temperature, color=Location)) + -->
<!--   labs(y="Annual temperature") -->
<!-- ``` -->

<!-- ## 2.1 -->

<!-- Add a trend line (loess fit) for each group. (Hint: use geom_smooth) -->

<!-- ```{r, include=show_results} -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year, !!sym(plotvar), color=Location)) + -->
<!--   geom_smooth(aes(Year, !!sym(plotvar),group=Location),method = "loess") + -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->

<!-- ## 2.2 -->

<!-- We can clearly see an upwards trend in each of the four locations. Next we want to see the relative temperature compared to the mean of the "Annual_temperature" for the years 1931-1950. For that, center "Annual_temperature" by subtracting the mean of the years 1931-1950. -->


<!-- ```{r, include=show_results} -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::group_by(Location) %>%  -->
<!--   dplyr::mutate(mean_temperature = mean(Annual_temperature[Year<1951]), -->
<!--                 Annual_temperature = Annual_temperature-mean_temperature, -->
<!--                 mean_sunshine = mean(Sunshine_duration[Year<1951]), -->
<!--                 Sunshine_duration = Sunshine_duration-mean_sunshine) %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year, !!sym(plotvar), color=Location)) + -->
<!--   # facet_wrap(~Location) + -->
<!--   geom_smooth(aes(Year, !!sym(plotvar)),method = "loess") + -->
<!--   # scale_color_viridis_d() + -->
<!--   labs(y="Change in Annual temperatue", -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->


<!-- ## 2.3 -->

<!-- Now we want to make the plot a bit nicer looking, try to reproduce the following. Hint: have a look at `theme` and `scale_x_continuous`. -->

<!-- ```{r, include=show_results} -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::group_by(Location) %>%  -->
<!--   dplyr::mutate(mean_temperature = mean(Annual_temperature[Year<1951]), -->
<!--                 Annual_temperature = Annual_temperature-mean_temperature, -->
<!--                 mean_sunshine = mean(Sunshine_duration[Year<1951]), -->
<!--                 Sunshine_duration = Sunshine_duration-mean_sunshine) %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year, !!sym(plotvar), color=Location)) + -->
<!--   geom_smooth(aes(Year, !!sym(plotvar)),method = "loess") + -->
<!--   scale_x_continuous(breaks = c(1930,1960,1990,2020)) + -->
<!--   theme(axis.text.x = element_text(angle=45, hjust=0.5, vjust = 0.5),  -->
<!--         panel.grid.minor = element_blank(), -->
<!--         panel.spacing.x = unit(1, "lines"), -->
<!--         panel.background = element_rect(fill="grey97"),  -->
<!--         strip.background = element_rect(fill="grey93"),  -->
<!--         strip.text = element_text(face="bold"), -->
<!--         legend.position = c(0.9,0.16),legend.title = element_blank(), -->
<!--           ) + -->
<!--   labs(x="", y="Change in Annual temperature", color="") -->
<!-- ``` -->



<!-- # 3 -->

<!-- In this exercise we will do a bar plot showing the mean number of Annual summer days faceted by location and summarized into 3 bins. Again we will develop the graph in multiple steps. -->
<!-- We want to combine the values into 3 bins of equal size. In other words we will calculate the mean value for the years 1931-1960, 1961-1990 and 1991-2020. Meaning we want a data.frame of the following format: -->

<!-- ```{r, include=show_results} -->
<!-- cutv <- c(1930,1960,1990,2020) -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   dplyr::mutate(Year = cut(Year, cutv, right = TRUE), -->
<!--                 Year = factor(Year, labels = c("1931-1960","1961-1990","1991-2020"))) %>%  -->
<!--   dplyr::group_by(Year, Location) %>%  -->
<!--   dplyr::summarise("mean_Annual_summer_days" = mean(na.omit(Annual_summer_days)), -->
<!--                    "sd_Annual_summer_days" = sd(na.omit(Annual_summer_days)))  -->
<!-- ``` -->


<!-- ## 3.1 -->

<!-- First exercise is to create the following barplot. (Hint use `facet_wrap(~Location)`) -->
<!-- ```{r, include=show_results} -->
<!-- plotvar <- plotvars[6] -->
<!-- cutv <- c(1930,1960,1990,2020) -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   dplyr::mutate(Year = cut(Year, cutv, right = TRUE), -->
<!--                 Year = factor(Year, labels = c("1931-1960","1961-1990","1991-2020"))) %>% #pull(Year) %>% unique -->
<!--   dplyr::group_by(Year, Location) %>%  -->
<!--   dplyr::summarise(!!sym(paste0("mean_",plotvar)) := mean(na.omit(!!sym(plotvar)))) %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year, !!sym(paste0("mean_",plotvar)), fill=Year), position = "dodge") + -->
<!--   facet_wrap(~Location) + -->
<!--   theme(axis.text.x = element_text(angle=45,hjust=1)) + -->
<!--   labs(x="", y="Mean number of annual summer days") -->
<!-- ``` -->


<!-- ## 3.2 -->

<!-- Since we aggregate data, and have some missing values we also want to show the error bars (i.e. standard deviation). (Hint use `geom_errorbar` and calculate the errorbar, +- 1 standard deviation (sd)) -->
<!-- ```{r, include=show_results} -->
<!-- plotvar <- plotvars[6] -->
<!-- cutv <- c(1930,1960,1990,2020) -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   dplyr::mutate(Year = cut(Year, cutv, right = TRUE), -->
<!--                 Year = factor(Year, labels = c("1931-1960","1961-1990","1991-2020"))) %>% #pull(Year) %>% unique -->
<!--   dplyr::group_by(Year, Location) %>%  -->
<!--   dplyr::summarise(!!sym(paste0("mean_",plotvar)) := mean(na.omit(!!sym(plotvar))), -->
<!--                    !!sym(paste0("sd_",plotvar)) := sd(na.omit(!!sym(plotvar)))) %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year, !!sym(paste0("mean_",plotvar)), fill=Year), position = "dodge") + -->
<!--   geom_errorbar(aes(x=Year, -->
<!--                     y=!!sym(paste0("mean_",plotvar)), -->
<!--                     ymin=!!sym(paste0("mean_",plotvar))-!!sym(paste0("sd_",plotvar)),  -->
<!--                     ymax=!!sym(paste0("mean_",plotvar))+!!sym(paste0("sd_",plotvar))), width=.2) + -->
<!--   facet_wrap(~Location) + -->
<!--   theme(axis.text.x = element_text(angle=45,hjust=1)) + -->
<!--   labs(x="", y="Mean number of annual summer days") -->
<!-- ``` -->


<!-- ## 3.4 -->

<!-- To get another view of the same data we switch to sina plots instead of bar plots. -->
<!-- ```{r, include=show_results} -->
<!-- plotvar <- plotvars[6] -->
<!-- cutv <- c(1930,1960,1990,2020) -->
<!-- climatedf_comp %>%  -->
<!--   dplyr::filter(Location %in% c("ZürichFluntern","Säntis","Samedan","LocarnoMonti")) %>% -->
<!--   dplyr::mutate(Year = cut(Year, cutv, right = TRUE), -->
<!--                 Year = factor(Year, labels = c("1931-1960","1961-1990","1991-2020"))) %>% #pull(Year) %>% unique -->
<!--   # dplyr::group_by(Year, Location) %>%  -->
<!--   # dplyr::summarise(!!sym(paste0("mean_",plotvar)) := mean(na.omit(!!sym(plotvar)))) %>%  -->
<!--   ggplot(aes(Year, !!sym(plotvar), fill=Year)) + -->
<!--   geom_violin(position = "dodge", draw_quantiles=0.5) + -->
<!--   ggforce::geom_sina() + -->
<!--   facet_wrap(~Location) + -->
<!--   theme(axis.text.x = element_text(angle=45,hjust=1)) + -->
<!--   labs(x="", y="Mean number of annual summer days") -->

<!-- ``` -->



<!-- # 4 -->

<!-- In this exercise we will look at the Annual Precipitation with respect to time. -->

<!-- ## 4.1  -->
<!-- First we will create a stacked barplot of the Annual Precipitation for all measured years.  -->

<!-- ```{r, include=show_results} -->
<!-- colorvar <- "Location" -->
<!-- climatedf_comp %>% -->
<!--   dplyr::group_by(Year) %>%  -->
<!--   # dplyr::mutate(Annual_Precipitation=Annual_Precipitation/sum(Annual_Precipitation)) %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year,!!sym(plotvar), fill=!!sym(colorvar)))+ -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->

<!-- ## 4.2 -->

<!-- The same as 4.1 but normalized per year so that we get a sense of the change of proportions over time. -->

<!-- ```{r, include=show_results} -->
<!-- colorvar <- "Location" -->
<!-- climatedf_comp %>% -->
<!--   dplyr::group_by(Year) %>%  -->
<!--   dplyr::mutate(Annual_Precipitation=Annual_Precipitation/sum(Annual_Precipitation)) %>%  -->
<!--   ggplot() + -->
<!--   geom_col(aes(Year,!!sym(plotvar), fill=!!sym(colorvar)))+ -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->

<!-- ## 4.3 -->

<!-- Next we will create a line plot with x-axis year and y-axis Annual_Precipitation, colored by location. -->
<!-- ```{r, include=show_results} -->
<!-- colorvar <- "Location" -->
<!-- climatedf_comp %>% -->
<!--   dplyr::group_by(Year) %>%  -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year,!!sym(plotvar), color=!!sym(colorvar)))+ -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->

<!-- ## 4.4 -->

<!-- Same as 4.3 but add a loess fit to get the trend per location.  -->

<!-- ```{r, include=show_results} -->
<!-- colorvar <- "Location" -->
<!-- climatedf_comp %>% -->
<!--   dplyr::group_by(Year) %>%  -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year,!!sym(plotvar), color=!!sym(colorvar)), size=0.2) + -->
<!--   geom_smooth(aes(Year,!!sym(plotvar),color=!!sym(colorvar)),method = "loess", alpha=0.1)+ -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->

<!-- ## 4.5 -->

<!-- Same as 4.4 but we transform the y-axis to a log10 to improve separation of the lines for little Annual_Precipitation. -->
<!-- ```{r, include=show_results} -->
<!-- colorvar <- "Location" -->
<!-- climatedf_comp %>% -->
<!--   dplyr::group_by(Year) %>%  -->
<!--   ggplot() + -->
<!--   geom_line(aes(Year,!!sym(plotvar), color=!!sym(colorvar)), size=0.2) + -->
<!--   geom_smooth(aes(Year,!!sym(plotvar),color=!!sym(colorvar)),method = "loess", alpha=0.1) + -->
<!--   scale_y_log10()+ -->
<!--   labs(y=stringr::str_replace_all(plotvar,"_"," "), -->
<!--        color=stringr::str_replace_all(colorvar,"_"," ")) -->
<!-- ``` -->









<!-- ```{r, eval=FALSE} -->
<!-- climatedf_comp %>%  -->
<!-- GGally::ggpairs(columns = c(1,3:12)) -->
<!-- ``` -->


