---
output:
  tufte::tufte_html:
    tufte_features: ["fonts"]
    css: "my_style.css"
---

# In-class tasks

We continue to dicuss the quality of the preprints

[Preprint 1](/static/preprint1.pdf) and online https://www.researchsquare.com/article/rs-100956/v3

[Preprint 2](/static/preprint2.pdf) and online https://www.medrxiv.org/content/10.1101/2020.03.03.20028423v3

And we will compare the actual peer reviewed publication of Preprint 2:
[Preprint 2 pulished](/static/preprint2Published.pdf) and online https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30287-5/fulltext


## Task 1

Discuss the results of the assessment in the plenum.

## Task 2

For Preprint 1: This is a clinical trial and hence it should be registered on clinicaltrials.gov. Do you find information on it?

## Task 3

For Preprint 2 exists a published version. Can you find any difference if you assessed this version with PRECHECK (not only in the yes/no but also in the content which leads to yes/no)?

## Task 4

Look at the medarxiv site for Preprint 2: what do you find on reporting guidelines? Which reporting guideline would be pertinent for this article? Do you find something on reporting guidelines in the published article? Do you find the policy of the journal regarding reporting guidelines?

## Task 5 (optional if time allows)
 
Find the journal policy on data sharing.

**Submission** you will answer some questions on Open Edx regarding Tasks 1-4 in the next step.
